#!/bin/bash
SNAPSHOT=`date +%Y%m%d-%H%M%S`
#curl -XPUT "10.11.19.188:9200/_snapshot/my_backup/filebeat.$SNAPSHOT?wait_for_completion=true { "indices": "filebeat-*"}"





#PUT /_snapshot/my_backup/bcp?wait_for_completion=true
#{
#"indices":"filebeat-*"
#}



curl -X PUT "10.11.19.188:9200/_snapshot/my_backup/filebeat.$SNAPSHOT?wait_for_completion=true" -H 'Content-Type: application/json' -d'
{
  "indices": "filebeat-*",
  "ignore_unavailable": true,
  "include_global_state": false
}
'

